
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    #volumes:
     # - /app/node_modules
     # - ./frontend:/app
    #working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true  
  new_apis:
    build: ./new_apis
    ports:
      - "5050:5050"
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very-strong-db-password
    volumes:
      - mongodb_data:/data/db 
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8888:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER : mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: very-strong-db-password
    depends_on:
       mongo:
        condition: service_healthy

volumes:
  mongodb_data:


    

